-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 19:12:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `IdROLES` INT NOT NULL AUTO_INCREMENT,
  `Nombres_Roles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdROLES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `idUSUARIOS` INT NOT NULL AUTO_INCREMENT,
  `usuarios_nombres` VARCHAR(45) NOT NULL,
  `usuario_contraseña` VARCHAR(45) NOT NULL,
  `usuario_correo` VARCHAR(45) NOT NULL,
  `ROLES_IdROLES` INT NOT NULL,
  PRIMARY KEY (`idUSUARIOS`),
  INDEX `fk_USUARIOS_ROLES_idx` (`ROLES_IdROLES` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`ROLES_IdROLES`)
    REFERENCES `mydb`.`ROLES` (`IdROLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `idCLIENTES` INT NOT NULL AUTO_INCREMENT,
  `USUARIOS_idUSUARIOS` INT NOT NULL,
  PRIMARY KEY (`idCLIENTES`),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`USUARIOS_idUSUARIOS` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_idUSUARIOS`)
    REFERENCES `mydb`.`USUARIOS` (`idUSUARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTILISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTILISTAS` (
  `idESTILISTAS` INT NOT NULL AUTO_INCREMENT,
  `USUARIOS_idUSUARIOS` INT NOT NULL,
  PRIMARY KEY (`idESTILISTAS`),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`USUARIOS_idUSUARIOS` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_USUARIOS10`
    FOREIGN KEY (`USUARIOS_idUSUARIOS`)
    REFERENCES `mydb`.`USUARIOS` (`idUSUARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CITAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CITAS` (
  `IdCITAS` INT NOT NULL AUTO_INCREMENT,
  `Citas_fechas` DATETIME NOT NULL,
  `CLIENTES_idCLIENTES` INT NOT NULL,
  PRIMARY KEY (`IdCITAS`),
  INDEX `fk_CITAS_CLIENTES1_idx` (`CLIENTES_idCLIENTES` ASC) VISIBLE,
  CONSTRAINT `fk_CITAS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_idCLIENTES`)
    REFERENCES `mydb`.`CLIENTES` (`idCLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTILISTAS_has_CITAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTILISTAS_has_CITAS` (
  `ESTILISTAS_idESTILISTAS` INT NOT NULL,
  `CITAS_IdCITAS` INT NOT NULL,
  `Esteticistas_estado` TINYINT NOT NULL,
  INDEX `fk_ESTILISTAS_has_CITAS_ESTILISTAS1_idx` (`ESTILISTAS_idESTILISTAS` ASC) VISIBLE,
  INDEX `fk_ESTILISTAS_has_CITAS_CITAS1_idx` (`CITAS_IdCITAS` ASC) VISIBLE,
  CONSTRAINT `fk_ESTILISTAS_has_CITAS_ESTILISTAS1`
    FOREIGN KEY (`ESTILISTAS_idESTILISTAS`)
    REFERENCES `mydb`.`ESTILISTAS` (`idESTILISTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILISTAS_has_CITAS_CITAS1`
    FOREIGN KEY (`CITAS_IdCITAS`)
    REFERENCES `mydb`.`CITAS` (`IdCITAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORMAS_DE_PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORMAS_DE_PAGOS` (
  `idFORMAS_DE_PAGOS` INT NOT NULL AUTO_INCREMENT,
  `pago_nombre` VARCHAR(45) NOT NULL,
  `estado_del_pago` TINYINT(0) NOT NULL,
  PRIMARY KEY (`idFORMAS_DE_PAGOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIOS` (
  `idSERVICIOS` INT NOT NULL AUTO_INCREMENT,
  `servicio_nombre` VARCHAR(45) NOT NULL,
  `servicio_valor` VARCHAR(45) NOT NULL,
  `servicio_cantidad` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idSERVICIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTOS` (
  `idPRODUCTOS` INT NOT NULL AUTO_INCREMENT,
  `producto_nombre` VARCHAR(45) NOT NULL,
  `producto_precio` VARCHAR(45) NOT NULL,
  `producto_cantidad` INT NOT NULL,
  PRIMARY KEY (`idPRODUCTOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FACTURAS` (
  `idFACTURAS` INT NOT NULL AUTO_INCREMENT,
  `factura_fecha` DATETIME NOT NULL,
  `factura_total_productos` DECIMAL(7,2) NOT NULL,
  `factura_total_servicios` DECIMAL(7,2) NOT NULL,
  `factura_total` DECIMAL(7,2) NOT NULL,
  `CLIENTES_idCLIENTES` INT NOT NULL,
  `FORMAS_DE_PAGOS_idFORMAS_DE_PAGOS` INT NOT NULL,
  `SERVICIOS_idSERVICIOS` INT NOT NULL,
  `PRODUCTOS_idPRODUCTOS` INT NOT NULL,
  PRIMARY KEY (`idFACTURAS`),
  INDEX `fk_FACTURAS_CLIENTES1_idx` (`CLIENTES_idCLIENTES` ASC) VISIBLE,
  INDEX `fk_FACTURAS_FORMAS_DE_PAGOS1_idx` (`FORMAS_DE_PAGOS_idFORMAS_DE_PAGOS` ASC) VISIBLE,
  INDEX `fk_FACTURAS_SERVICIOS1_idx` (`SERVICIOS_idSERVICIOS` ASC) VISIBLE,
  INDEX `fk_FACTURAS_PRODUCTOS1_idx` (`PRODUCTOS_idPRODUCTOS` ASC) VISIBLE,
  CONSTRAINT `fk_FACTURAS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_idCLIENTES`)
    REFERENCES `mydb`.`CLIENTES` (`idCLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURAS_FORMAS_DE_PAGOS1`
    FOREIGN KEY (`FORMAS_DE_PAGOS_idFORMAS_DE_PAGOS`)
    REFERENCES `mydb`.`FORMAS_DE_PAGOS` (`idFORMAS_DE_PAGOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURAS_SERVICIOS1`
    FOREIGN KEY (`SERVICIOS_idSERVICIOS`)
    REFERENCES `mydb`.`SERVICIOS` (`idSERVICIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURAS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_idPRODUCTOS`)
    REFERENCES `mydb`.`PRODUCTOS` (`idPRODUCTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMISIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMISIONES` (
  `IdCOMISIONES` INT NOT NULL AUTO_INCREMENT,
  `comision_pagar` VARCHAR(45) NOT NULL,
  `comision_estado_pago` TINYINT(0) NOT NULL,
  `ESTILISTAS_idESTILISTAS` INT NOT NULL,
  `FACTURAS_idFACTURAS` INT NOT NULL,
  PRIMARY KEY (`IdCOMISIONES`),
  INDEX `fk_COMISIONES_ESTILISTAS1_idx` (`ESTILISTAS_idESTILISTAS` ASC) VISIBLE,
  INDEX `fk_COMISIONES_FACTURAS1_idx` (`FACTURAS_idFACTURAS` ASC) VISIBLE,
  CONSTRAINT `fk_COMISIONES_ESTILISTAS1`
    FOREIGN KEY (`ESTILISTAS_idESTILISTAS`)
    REFERENCES `mydb`.`ESTILISTAS` (`idESTILISTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMISIONES_FACTURAS1`
    FOREIGN KEY (`FACTURAS_idFACTURAS`)
    REFERENCES `mydb`.`FACTURAS` (`idFACTURAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
